version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
platform: Any CPU
before_build:
  - nuget restore
build:
  project: Msiler.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: '**\*.vsix'
  name: VSIX Extension
install:
- cmd: git submodule update --init --recursive